name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
    deploy-to-google-cloud:
        name: Deploy to Google Cloud
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            deployments: write
        environment: staging

        steps:          
        - uses: google-github-actions/auth@v2
          with:
            credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
            project_id: ${{ vars.GCP_PROJECT_ID }}